In [1]:
from pathlib import Path
import pandas as pd

In [2]:
ROOT_DIR = Path("../")
DATA_DIR = ROOT_DIR / "data"
RAW_DATA_DIR = DATA_DIR / "00_raw" / "text"
OUTPUT_DATA_ROOT_DIR = DATA_DIR / "01_processed" / "Suryaghar Call Analysis"
OUTPUT_DATA_ROOT_DIR.mkdir(parents=True, exist_ok=True)

In [3]:
df_1 = pd.read_csv(RAW_DATA_DIR / "pm_suryaghar_stage_wise_report_20260423_152452.csv")
df_2 = pd.read_csv(RAW_DATA_DIR / "pm_suryaghar_stage_wise_report_20260423_152457.csv")

In [4]:
df_1

,Call Datetime,App ID,Name,Mobile,Stage,Remark,call connect hua ?,Kya aap abhi bhi PM Surya Ghar Yojana ke tahat rooftop solar lagwana chahte hain?,Kya kisi vendor ne aapse sampark kiya hai?,"Kya aapne kisi vendor ko final kar liya hai, par portal par select nahi kiya?",Vendor select na karne ka mukhya karan kya hai?,Aapko vendor select karne ke liye kis prakar ki sahayata chahiye?
0,2026-04-23 09:53:57,4852370,BHARAT SINGH,9.752844e+09,Vendor Selection,आवेदक सोलर लगवाने के इच्‍छुक नही हैं एवं किसी ...,connected,NAHI,NAHI,NAHI,OTHERS,Abhi interested nahi
1,2026-04-23 09:46:55,4849443,SH.VIJAY KUMAR NATHULAL,7.880694e+09,Vendor Selection,आवेदक द्वारा कॉल रिसीव नहीं किया गया।,Not connected,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable
2,2026-04-23 09:45:28,4849095,ARTI KOSHTA,8.816000e+09,Vendor Selection,आवेदक द्वारा कॉल रिसीव नहीं किया गया।,Not connected,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable
3,2026-04-23 09:38:17,4841119,RAHUL MANOHAR LAL,9.179263e+09,Vendor Selection,आवेदक द्वारा कॉल रिसीव नहीं किया गया।,Not connected,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable
4,2026-04-23 09:34:29,4874882,KAMLESH BHOLA YADAV,9.589044e+09,Vendor Selection,आवेदक बात करने के इच्‍छुक नही हैं।,connected,Not Applicable,Not Applicable,Not Applicable,OTHERS,Abhi interested nahi
...,...,...,...,...,...,...,...,...,...,...,...,...
1207,2026-03-25 07:13:30,1002444,SEETARAM NAMDEV KANCHHEDILAL NAMDEV,9.977435e+09,Vendor Selection,"Financiall problem hai,or loan nahi lena chahte",connected,Soch rahe hain,NAHI,NAHI,OTHERS,Abhi interested nahi
1208,2026-03-25 07:13:30,1002444,SEETARAM NAMDEV KANCHHEDILAL NAMDEV,9.977435e+09,Vendor Selection,"Financiall problem hai,or loan nahi lena chahte",connected,Soch rahe hain,NAHI,NAHI,OTHERS,Abhi interested nahi
1209,2026-03-24 10:10:56,1002333,CHAIN SINGH,9.424691e+09,Vendor Selection,Not answering,Not connected,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable
1210,2026-03-24 07:51:41,1440073,GANGARAM MOTILAL,9.926300e+09,Vendor Selection,"Busy,baad me baat karenge",connected,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable
1211,2026-03-16 12:23:39,8737179,Shubha Sharma,NaN,Vendor Selection,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df_1[df_1["App ID"] == 516026]

,Call Datetime,App ID,Name,Mobile,Stage,Remark,call connect hua ?,Kya aap abhi bhi PM Surya Ghar Yojana ke tahat rooftop solar lagwana chahte hain?,Kya kisi vendor ne aapse sampark kiya hai?,"Kya aapne kisi vendor ko final kar liya hai, par portal par select nahi kiya?",Vendor select na karne ka mukhya karan kya hai?,Aapko vendor select karne ke liye kis prakar ki sahayata chahiye?
912,2026-04-02 10:54:09,516026,VIJAY TEJLA BARIYA,7.000909e+09,Vendor Selection,आवेदक का विद्युत बिल कम होने के कारण वेंडर ने ...,connected,HAAN,HAAN,NAHI,OTHERS,Not Applicable
913,2026-04-02 10:54:09,516026,VIJAY TEJLA BARIYA,7.000909e+09,Vendor Selection,आवेदक का विद्युत बिल कम होने के कारण वेंडर ने ...,connected,HAAN,HAAN,NAHI,OTHERS,Not Applicable
914,2026-04-02 10:54:09,516026,VIJAY TEJLA BARIYA,7.000909e+09,Vendor Selection,आवेदक का विद्युत बिल कम होने के कारण वेंडर ने ...,connected,HAAN,HAAN,NAHI,OTHERS,Not Applicable
915,2026-04-02 10:47:22,516026,VIJAY TEJLA BARIYA,7.000909e+09,Vendor Selection,आवेदक द्वारा कॉल रिसीव नहीं किया गया।,Not connected,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable

In [6]:
df_1.groupby("App ID")["Name"].count()

App ID
2599       1
7297       1
7329       1
11386      1
12531      4
          ..
7055829    1
7077341    1
7090647    1
7094252    1
8737179    1
Name: Name, Length: 985, dtype: int64

In [7]:
df_1["Mobile"].isna().sum()

4

In [8]:
df = pd.concat([df_1, df_2], ignore_index=True)

In [9]:
df

,Call Datetime,App ID,Name,Mobile,Stage,Remark,call connect hua ?,Kya aap abhi bhi PM Surya Ghar Yojana ke tahat rooftop solar lagwana chahte hain?,Kya kisi vendor ne aapse sampark kiya hai?,"Kya aapne kisi vendor ko final kar liya hai, par portal par select nahi kiya?",Vendor select na karne ka mukhya karan kya hai?,Aapko vendor select karne ke liye kis prakar ki sahayata chahiye?,Call connect hua?,Kya aapke yahan solar installation ka kaam shuru ya complete ho gaya hai?,Vendor select karne ke baad kitna samay ho gaya hai?,Installation delay hone ka mukhya karan kya hai?,Aapko installation jaldi karwane ke liye kis prakar ki sahayata chahiye?
0,2026-04-23 09:53:57,4852370,BHARAT SINGH,9.752844e+09,Vendor Selection,आवेदक सोलर लगवाने के इच्‍छुक नही हैं एवं किसी ...,connected,NAHI,NAHI,NAHI,OTHERS,Abhi interested nahi,NaN,NaN,NaN,NaN,NaN
1,2026-04-23 09:46:55,4849443,SH.VIJAY KUMAR NATHULAL,7.880694e+09,Vendor Selection,आवेदक द्वारा कॉल रिसीव नहीं किया गया।,Not connected,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable,NaN,NaN,NaN,NaN,NaN
2,2026-04-23 09:45:28,4849095,ARTI KOSHTA,8.816000e+09,Vendor Selection,आवेदक द्वारा कॉल रिसीव नहीं किया गया।,Not connected,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable,NaN,NaN,NaN,NaN,NaN
3,2026-04-23 09:38:17,4841119,RAHUL MANOHAR LAL,9.179263e+09,Vendor Selection,आवेदक द्वारा कॉल रिसीव नहीं किया गया।,Not connected,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable,NaN,NaN,NaN,NaN,NaN
4,2026-04-23 09:34:29,4874882,KAMLESH BHOLA YADAV,9.589044e+09,Vendor Selection,आवेदक बात करने के इच्‍छुक नही हैं।,connected,Not Applicable,Not Applicable,Not Applicable,OTHERS,Abhi interested nahi,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2578,2026-03-16 12:19:00,8737249,Mohit Kumar Soni,NaN,Upload Agreement,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2579,2026-03-16 11:12:41,8730647,RAMBHAROSE BABULAL,NaN,Upload Agreement,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2580,2026-03-16 10:50:53,8730719,KARAN KUMAR GWALA SO RADHESHYAM GWALA,NaN,Upload Agreement,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2581,2026-03-16 10:41:07,8730765,SHRI RAKESH CHUNNILAL,NaN,Upload Agreement,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2582,2026-03-16 10:15:54,8730841,DAOOD IMRAN JI RAWATIWALA,NaN,Upload Agreement,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
df["Remark"].value_counts()

Remark
आवेदक द्वारा कॉल रिसीव नहीं किया गया।                                                                               419
आवेदक द्वारा कॉल रिसिव नहीं किया गया है।                                                                            158
आवेदक ने कॉल रिसीव नही किया                                                                                         145
आवेदक द्वारा कॉल रिसीव नहीं किया गया                                                                                100
आवेदक को योजना कि प्रक्रिया समझ नही आई थी,उन्‍हें आवश्‍यक जानकारी प्रदान कर दी गई तथा वे अब वेंडर का चयन करेंगे।     72
                                                                                                                   ...
बिजली का बिल कम आता है इसलिए नही लगा रहै है।                                                                          1
आवेदक सौलर पैनल नही लगाना चाहते है।                                                                                   1
आवेदक सौलर पैनल नही लगाना चाहते है। उन्‍हे पवन चक्‍की लगाना है।                                                       1
आवेदक सौलर पैनल लगवाना चाहते है।                                                                                      1
test                                                                                                                  1
Name: count, Length: 702, dtype: int64

In [10]:
# drop all duplicates in the Remark column from df
df_unique_remark = df.drop_duplicates(subset=["Remark"])

In [11]:
df

,Call Datetime,App ID,Name,Mobile,Stage,Remark,call connect hua ?,Kya aap abhi bhi PM Surya Ghar Yojana ke tahat rooftop solar lagwana chahte hain?,Kya kisi vendor ne aapse sampark kiya hai?,"Kya aapne kisi vendor ko final kar liya hai, par portal par select nahi kiya?",Vendor select na karne ka mukhya karan kya hai?,Aapko vendor select karne ke liye kis prakar ki sahayata chahiye?,Call connect hua?,Kya aapke yahan solar installation ka kaam shuru ya complete ho gaya hai?,Vendor select karne ke baad kitna samay ho gaya hai?,Installation delay hone ka mukhya karan kya hai?,Aapko installation jaldi karwane ke liye kis prakar ki sahayata chahiye?
0,2026-04-23 09:53:57,4852370,BHARAT SINGH,9.752844e+09,Vendor Selection,आवेदक सोलर लगवाने के इच्‍छुक नही हैं एवं किसी ...,connected,NAHI,NAHI,NAHI,OTHERS,Abhi interested nahi,NaN,NaN,NaN,NaN,NaN
1,2026-04-23 09:46:55,4849443,SH.VIJAY KUMAR NATHULAL,7.880694e+09,Vendor Selection,आवेदक द्वारा कॉल रिसीव नहीं किया गया।,Not connected,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable,NaN,NaN,NaN,NaN,NaN
2,2026-04-23 09:45:28,4849095,ARTI KOSHTA,8.816000e+09,Vendor Selection,आवेदक द्वारा कॉल रिसीव नहीं किया गया।,Not connected,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable,NaN,NaN,NaN,NaN,NaN
3,2026-04-23 09:38:17,4841119,RAHUL MANOHAR LAL,9.179263e+09,Vendor Selection,आवेदक द्वारा कॉल रिसीव नहीं किया गया।,Not connected,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable,NaN,NaN,NaN,NaN,NaN
4,2026-04-23 09:34:29,4874882,KAMLESH BHOLA YADAV,9.589044e+09,Vendor Selection,आवेदक बात करने के इच्‍छुक नही हैं।,connected,Not Applicable,Not Applicable,Not Applicable,OTHERS,Abhi interested nahi,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2578,2026-03-16 12:19:00,8737249,Mohit Kumar Soni,NaN,Upload Agreement,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2579,2026-03-16 11:12:41,8730647,RAMBHAROSE BABULAL,NaN,Upload Agreement,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2580,2026-03-16 10:50:53,8730719,KARAN KUMAR GWALA SO RADHESHYAM GWALA,NaN,Upload Agreement,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2581,2026-03-16 10:41:07,8730765,SHRI RAKESH CHUNNILAL,NaN,Upload Agreement,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2582,2026-03-16 10:15:54,8730841,DAOOD IMRAN JI RAWATIWALA,NaN,Upload Agreement,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# get one long string from Remarks with each remark separated by incrementing number and on new line
df_unique_remark["numbered_remarks"] = df_unique_remark.index.astype(str) + ": " + df_unique_remark["Remark"]

/var/folders/99/cwxq7sdx5d94rqxj57_crqbc0000gn/T/ipykernel_29824/430788480.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_unique_remark["numbered_remarks"] = df_unique_remark.index.astype(str) + ": " + df_unique_remark["Remark"]

In [19]:
txt = df_unique_remark["numbered_remarks"].str.cat(sep="\n")
with open(OUTPUT_DATA_ROOT_DIR / "numbered_remarks.txt", "w") as f:
    f.write(txt)